"""Isaac Sim backend for the Vega (vega_1, parallel-gripper variant).

Public surface intentionally mirrors the subset of dexcontrol.robot.Robot used
by run_demo.py (`execute_trajectory`, `get_joint_pos_dict`, `sensors.*.get_obs`,
context-manager shutdown). Phase 2 swaps `SimVegaRobot(...)` for
`dexcontrol.robot.Robot()` at the construction site; call sites above this
class don't change.

Asset note: we render the *official pre-built USD* published in the
dexmate-urdf GitHub releases, not a live URDF import. Isaac Sim 5.1's URDF
importer silently drops this robot's `.glb` visual meshes (it imports only the
`.obj` collision geometry), so a URDF import yields an invisible robot -- physics
works but there is nothing to render. The released USD is generated by Dexmate's
own Isaac Sim pipeline and carries the full visual meshes + materials. We still
read joint *limits* from the dexmate_urdf URDF (see action_chunks.parse_joint_limits);
the URDF remains the source of truth for kinematic metadata.

Must be imported only after `isaacsim.SimulationApp(...)` has already been
constructed by the entry point (run_demo.py) -- Isaac Sim requires the app to
exist before any other `isaacsim.*` submodule is imported.
"""

from __future__ import annotations

import time
import urllib.request
import zipfile
from pathlib import Path
from typing import Any

import numpy as np
import omni.kit.commands
import omni.usd
from dexmate_urdf import robots as dexmate_robots
from isaacsim.core.api import World
from isaacsim.core.api.objects import VisualCuboid
from isaacsim.core.prims import SingleArticulation
from isaacsim.core.utils.stage import add_reference_to_stage
from isaacsim.core.utils.types import ArticulationAction
from isaacsim.core.utils.viewports import set_camera_view
from isaacsim.sensors.camera import Camera
from pxr import Usd, UsdPhysics

# URDF path (from the dexmate_urdf package) -- used ONLY for joint-limit
# metadata by action_chunks.parse_joint_limits, not as the sim asset.
URDF_PATH = str(dexmate_robots.humanoid.vega_1.vega_1_gripper.urdf)

# Official pre-built USD asset (has visual meshes + materials). Pinned to the
# same release as the installed dexmate-urdf (0.8.4).
_RELEASE_TAG = "v0.8.4"
_USD_ZIP_URL = (
    f"https://github.com/dexmate-ai/dexmate-urdf/releases/download/"
    f"{_RELEASE_TAG}/vega_1_gripper.zip"
)
_ASSET_DIR = Path(__file__).parent / "assets" / f"vega_1_gripper_{_RELEASE_TAG}"
_USD_FILE = _ASSET_DIR / "vega_1_gripper.usd"

ROBOT_PRIM_PATH = "/World/Vega"

# URDF/USD link names for the four camera mounts (see vega_1_gripper).
_CAM_LINKS = {
    "head_left": "zed_left_camera",
    "head_right": "zed_right_camera",
    "wrist_left": "L_camera_link",
    "wrist_right": "R_camera_link",
}

CAMERA_RESOLUTION = (640, 480)

# Position-drive gains (kp, kd) per component. The official Vega USD ships very
# soft drives (kp=100, kd=1) -- far too weak to hold the arms/torso against
# gravity, so the robot reaches a pose then sags ("falls down"). These values
# hold the standing pose to ~0.01 rad without the instability seen at very high
# kp on the low-inertia arm joints. Torso is stiffest (it holds the whole
# upper body); arm kp kept moderate to stay stable at 60 Hz.
DRIVE_GAINS: dict[str, tuple[float, float]] = {
    "left_arm": (3000.0, 200.0),
    "right_arm": (3000.0, 200.0),
    "head": (2000.0, 60.0),
    "torso": (60000.0, 1500.0),
    "left_hand": (1000.0, 30.0),
    "right_hand": (1000.0, 30.0),
}


def get_vega_usd() -> str:
    """Return the local path to the official Vega USD, downloading+caching it
    from the dexmate-urdf GitHub release on first use."""
    if _USD_FILE.exists():
        return str(_USD_FILE)
    _ASSET_DIR.mkdir(parents=True, exist_ok=True)
    zip_path = _ASSET_DIR / "vega_1_gripper.zip"
    print(f"Downloading official Vega USD from {_USD_ZIP_URL} ...", flush=True)
    urllib.request.urlretrieve(_USD_ZIP_URL, zip_path)
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(_ASSET_DIR)
    zip_path.unlink(missing_ok=True)
    if not _USD_FILE.exists():
        raise RuntimeError(f"Expected {_USD_FILE} after extraction, not found")
    print(f"Vega USD cached at {_USD_FILE}", flush=True)
    return str(_USD_FILE)


def _find_prim_path(stage: Usd.Stage, root_path: str, name: str) -> str:
    """Find the first descendant prim of root_path named exactly `name`."""
    for prim in Usd.PrimRange(stage.GetPrimAtPath(root_path)):
        if prim.GetName() == name:
            return prim.GetPath().pathString
    raise RuntimeError(f"Could not find prim named '{name}' under {root_path}")


def _wait_for_frame(world: World, getter, max_steps: int = 60):
    """Step until a camera getter (get_rgb/get_depth) stops returning None."""
    for _ in range(max_steps):
        frame = getter()
        if frame is not None:
            return frame
        world.step(render=True)
    raise RuntimeError("Camera never produced a frame within the warmup budget")


class _MultiStreamCameraSensor:
    """Mirrors dexcontrol's head_camera: get_obs(obs_keys=[...]) -> {key: {...}}."""

    def __init__(self, streams: dict[str, Camera]):
        self._streams = streams

    def get_obs(
        self, obs_keys: list[str] | None = None, include_timestamp: bool = True
    ) -> dict[str, Any]:
        keys = obs_keys or list(self._streams.keys())
        now_ns = time.time_ns()
        out: dict[str, Any] = {}
        for key in keys:
            cam = self._streams.get(key)
            if cam is None:
                continue
            data = cam.get_depth() if key == "depth" else cam.get_rgb()
            out[key] = {"data": data, "timestamp_ns": now_ns, "receive_time_ns": now_ns}
        return out

    def wait_for_active(self, timeout: float = 5.0) -> bool:
        return True


class _SingleStreamCameraSensor:
    """Mirrors dexcontrol's wrist cameras: get_obs() -> flat {"data": ..., ...}."""

    def __init__(self, camera: Camera):
        self._camera = camera

    def get_obs(
        self, obs_keys: list[str] | None = None, include_timestamp: bool = True
    ) -> dict[str, Any]:
        now_ns = time.time_ns()
        return {"data": self._camera.get_rgb(), "timestamp_ns": now_ns, "receive_time_ns": now_ns}

    def wait_for_active(self, timeout: float = 5.0) -> bool:
        return True


class _Sensors:
    """Plain attribute bag, mirroring `dexcontrol.Robot().sensors`."""


class SimVegaRobot:
    """Isaac Sim stand-in for dexcontrol.robot.Robot (vega_1 gripper variant)."""

    def __init__(self, physics_dt: float = 1.0 / 60.0, add_scene_props: bool = False) -> None:
        from action_chunks import JOINT_NAMES

        self._world = World(physics_dt=physics_dt, rendering_dt=physics_dt)
        self._world.scene.add_default_ground_plane()
        omni.kit.commands.execute(
            "CreatePrim",
            prim_path="/World/DomeLight",
            prim_type="DomeLight",
            attributes={"inputs:intensity": 1000.0},
        )
        if add_scene_props:
            self._add_scene_props()

        # Reference the official pre-built USD, then load its payload so the
        # visual meshes compose into the stage (the whole robot body hangs off a
        # single payload at the reference root).
        usd_path = get_vega_usd()
        add_reference_to_stage(usd_path=usd_path, prim_path=ROBOT_PRIM_PATH)
        stage = omni.usd.get_context().get_stage()
        robot_prim = stage.GetPrimAtPath(ROBOT_PRIM_PATH)
        payloads = [
            p.GetPath()
            for p in Usd.PrimRange(robot_prim, Usd.PrimAllPrimsPredicate)
            if p.HasAuthoredPayloads()
        ]
        if payloads:
            stage.LoadAndUnload(set(payloads), set())

        # The articulation root is the fixed-base joint prim inside the asset.
        art_root = None
        for prim in Usd.PrimRange(robot_prim):
            if prim.HasAPI(UsdPhysics.ArticulationRootAPI):
                art_root = prim.GetPath().pathString
                break
        if art_root is None:
            raise RuntimeError("No ArticulationRoot found under the Vega asset")

        self._articulation = SingleArticulation(prim_path=art_root, name="vega")
        self._world.reset()
        self._articulation.initialize()

        self._dof_index: dict[str, dict[str, int]] = {
            component: {j: self._articulation.get_dof_index(j) for j in joints}
            for component, joints in JOINT_NAMES.items()
        }
        # Parallel-gripper mimic jaw: dexcontrol commands 1 DOF (L/R_gripper_j1)
        # but the USD has a second jaw joint (j2). Drive j2 to match j1 so both
        # jaws move; state still reports only the 1 DOF dexcontrol expects.
        self._gripper_mimic: dict[str, int] = {}
        for comp, j2 in (("left_hand", "L_gripper_j2"), ("right_hand", "R_gripper_j2")):
            try:
                self._gripper_mimic[comp] = self._articulation.get_dof_index(j2)
            except Exception:
                pass

        self._set_drive_gains()

        # Cameras: a fresh child prim under each mount link (attaching the camera
        # schema directly on the link prim -- which carries rigid-body physics --
        # crashes the renderer natively on this build).
        cameras: dict[str, Camera] = {}
        for key, link_name in _CAM_LINKS.items():
            link_path = _find_prim_path(stage, ROBOT_PRIM_PATH, link_name)
            cam = Camera(
                prim_path=f"{link_path}/Camera",
                name=f"{key}_cam",
                resolution=CAMERA_RESOLUTION,
            )
            cam.initialize()
            cameras[key] = cam
        cameras["head_left"].add_distance_to_image_plane_to_frame()
        self._camera_prim_paths = {k: c.prim_path for k, c in cameras.items()}

        # Point the GUI viewport camera at the robot so it's framed on screen.
        set_camera_view(eye=np.array([3.2, 2.6, 1.4]), target=np.array([0.15, 0.0, 0.5]))

        # Warm up the render products until frames are available.
        _wait_for_frame(self._world, cameras["head_left"].get_rgb)
        _wait_for_frame(self._world, cameras["head_left"].get_depth)
        for key in ("head_right", "wrist_left", "wrist_right"):
            _wait_for_frame(self._world, cameras[key].get_rgb)

        self.sensors = _Sensors()
        self.sensors.head_camera = _MultiStreamCameraSensor(
            {"left_rgb": cameras["head_left"], "right_rgb": cameras["head_right"], "depth": cameras["head_left"]}
        )
        self.sensors.left_wrist_camera = _SingleStreamCameraSensor(cameras["wrist_left"])
        self.sensors.right_wrist_camera = _SingleStreamCameraSensor(cameras["wrist_right"])

    def enable_live_camera_windows(self) -> None:
        """Open live viewport windows (GUI only) showing each robot RGB camera
        feed in real time, alongside the main third-person viewport. Each window
        is bound to a camera prim and re-renders every world.step(), so it stays
        live as the robot moves. No-op / best-effort if the viewport UI isn't
        available (e.g. headless)."""
        try:
            from omni.kit.viewport.utility import create_viewport_window
            from pxr import Sdf
        except Exception as e:  # pragma: no cover - GUI-only path
            print(f"Live camera windows unavailable: {e}", flush=True)
            return
        # (key, screen x, y) -- small tiled windows in the top-left.
        layout = [
            ("head_left", 30, 60),
            ("head_right", 370, 60),
            ("wrist_left", 30, 350),
            ("wrist_right", 370, 350),
        ]
        self._camera_windows = []
        for key, x, y in layout:
            path = self._camera_prim_paths.get(key)
            if path is None:
                continue
            win = create_viewport_window(
                name=f"vega: {key}",
                camera_path=Sdf.Path(path),
                width=320, height=240, position_x=x, position_y=y,
            )
            self._camera_windows.append(win)

    def _add_scene_props(self) -> None:
        """A few colored cubes resting on the floor in front of the robot, so the
        camera feeds have something to look at (and as stand-in manipulation
        targets for later). Placed at ground level (z = size/2) so they sit on
        the floor rather than floating."""
        size = 0.12
        z = size / 2.0
        cube_layout = [
            ((1.1, 0.0, z), (0.9, 0.1, 0.1)),
            ((1.0, 0.45, z), (0.1, 0.9, 0.1)),
            ((1.0, -0.45, z), (0.1, 0.1, 0.9)),
        ]
        for i, (position, color) in enumerate(cube_layout):
            self._world.scene.add(
                VisualCuboid(
                    prim_path=f"/World/marker_cube_{i}",
                    name=f"marker_cube_{i}",
                    position=np.array(position),
                    size=size,
                    color=np.array(color),
                )
            )

    def get_joint_pos(self, component: str) -> np.ndarray:
        positions = self._articulation.get_joint_positions()
        idx = list(self._dof_index[component].values())
        return positions[idx]

    def get_joint_pos_dict(self, component: str | list[str]) -> dict[str, float]:
        components = [component] if isinstance(component, str) else component
        positions = self._articulation.get_joint_positions()
        out: dict[str, float] = {}
        for c in components:
            for name, idx in self._dof_index[c].items():
                out[name] = float(positions[idx])
        return out

    def execute_trajectory(
        self,
        trajectory: dict[str, np.ndarray],
        control_hz: float = 60.0,
        relative: bool = False,
    ) -> None:
        """Stream a `{component: (T, dof)}` action chunk to the articulation."""
        components = list(trajectory.keys())
        dof_indices = np.array(
            [idx for c in components for idx in self._dof_index[c].values()]
        )
        horizon = len(next(iter(trajectory.values())))

        if relative:
            offset = {c: self.get_joint_pos(c) for c in components}
            trajectory = {c: offset[c][None, :] + trajectory[c] for c in components}

        controller = self._articulation.get_articulation_controller()
        dt = 1.0 / control_hz
        for step in range(horizon):
            positions = np.concatenate([trajectory[c][step] for c in components])
            controller.apply_action(
                ArticulationAction(joint_positions=positions, joint_indices=dof_indices)
            )
            t0 = time.time()
            self._world.step(render=True)
            elapsed = time.time() - t0
            if elapsed < dt:
                time.sleep(dt - elapsed)

    def _set_drive_gains(self) -> None:
        """Stiffen the position drives so the robot holds its pose against gravity
        (the official USD's default kp=100/kd=1 is far too soft and it sags)."""
        controller = self._articulation.get_articulation_controller()
        kps, kds = controller.get_gains()
        kps = np.asarray(kps, dtype=float).copy()
        kds = np.asarray(kds, dtype=float).copy()
        for comp, (kp, kd) in DRIVE_GAINS.items():
            for idx in self._dof_index[comp].values():
                kps[idx] = kp
                kds[idx] = kd
            if comp in self._gripper_mimic:
                kps[self._gripper_mimic[comp]] = kp
                kds[self._gripper_mimic[comp]] = kd
        controller.set_gains(kps=kps, kds=kds)

    # ---- Step-level control surface (used by the Zenoh sim-server bridge) ----
    def set_joint_targets(self, targets: dict[str, np.ndarray]) -> None:
        """Apply position targets for the given components (persisted by the
        position drives; does not step). Gripper components drive both jaws."""
        idxs: list[int] = []
        vals: list[float] = []
        for comp, arr in targets.items():
            arr = np.asarray(arr, dtype=float).ravel()
            for k, idx in enumerate(self._dof_index[comp].values()):
                idxs.append(idx)
                vals.append(float(arr[k]))
            if comp in self._gripper_mimic:
                idxs.append(self._gripper_mimic[comp])
                vals.append(float(arr[0]))
        if not idxs:
            return
        self._articulation.get_articulation_controller().apply_action(
            ArticulationAction(
                joint_positions=np.array(vals, dtype=float),
                joint_indices=np.array(idxs),
            )
        )

    def step_once(self, render: bool = True) -> None:
        self._world.step(render=render)

    def move_to_pose(self, pose: dict[str, np.ndarray], steps: int = 120,
                     render: bool = True) -> None:
        """Smoothly (cosine ease) drive from the current pose to `pose` over
        `steps` physics steps. Ramping avoids flinging the stiff position drives
        that an instant setpoint jump would cause."""
        start = {c: self.get_joint_pos(c) for c in pose}
        target = {c: np.asarray(pose[c], dtype=float) for c in pose}
        for s in range(steps):
            e = 0.5 * (1.0 - np.cos(np.pi * (s + 1) / steps))
            self.set_joint_targets(
                {c: start[c] + e * (target[c] - start[c]) for c in pose}
            )
            self.step_once(render=render)

    def read_joint_states(self) -> dict[str, tuple[np.ndarray, np.ndarray]]:
        """Return {component: (pos, vel)} for every commanded component."""
        pos_all = self._articulation.get_joint_positions()
        vel_all = self._articulation.get_joint_velocities()
        out: dict[str, tuple[np.ndarray, np.ndarray]] = {}
        for comp, idxmap in self._dof_index.items():
            idx = list(idxmap.values())
            out[comp] = (pos_all[idx], vel_all[idx])
        return out

    def shutdown(self) -> None:
        pass

    def __enter__(self) -> "SimVegaRobot":
        return self

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        self.shutdown()
